import { EntityPermissions } from "./EntityPermissions";

export class UserEntityPermissions  {
    Team:EntityPermissions = new EntityPermissions();
    MasterUnit:EntityPermissions = new EntityPermissions();
    Project:EntityPermissions = new EntityPermissions();
    Area:EntityPermissions = new EntityPermissions();
    PaymentPlan:EntityPermissions= new EntityPermissions();
    Developer:EntityPermissions= new EntityPermissions();
    Role:EntityPermissions= new EntityPermissions();
    Contact:EntityPermissions= new EntityPermissions();
    Unit:EntityPermissions= new EntityPermissions();
    Country:EntityPermissions= new EntityPermissions();
    User:EntityPermissions= new EntityPermissions();
    UnitCategory:EntityPermissions= new EntityPermissions();
    Government:EntityPermissions= new EntityPermissions();
    Order:EntityPermissions= new EntityPermissions();
    Lead:EntityPermissions= new EntityPermissions();
    LeadType:EntityPermissions= new EntityPermissions();
    LeadSource:EntityPermissions= new EntityPermissions();
    Company:EntityPermissions= new EntityPermissions();
    Opportunity:EntityPermissions= new EntityPermissions();
    QualifiedLead:EntityPermissions= new EntityPermissions();
    FeaturedElement:EntityPermissions= new EntityPermissions();
    Transactions:EntityPermissions= new EntityPermissions();
    Dashboard:EntityPermissions= new EntityPermissions();
    Subscriber:EntityPermissions= new EntityPermissions();
    PropertyValuation:EntityPermissions= new EntityPermissions();
    DisqualifiedLead:EntityPermissions= new EntityPermissions();
    AreaDistrict:EntityPermissions= new EntityPermissions();
    SellingRequest:EntityPermissions= new EntityPermissions();
    ADS:EntityPermissions= new EntityPermissions();
    Favourite:EntityPermissions= new EntityPermissions();
    UnitFeature:EntityPermissions= new EntityPermissions();
    Amenity:EntityPermissions= new EntityPermissions();
    ProjectService:EntityPermissions= new EntityPermissions();
    Entity:EntityPermissions= new EntityPermissions();
    SelectedUnit:EntityPermissions= new EntityPermissions();
    Review:EntityPermissions= new EntityPermissions();
    Ticket:EntityPermissions= new EntityPermissions();
    Target:EntityPermissions= new EntityPermissions();
}